#!/usr/bin/env bash
#
# Upload a directory to s3://bohdan-sudoku/ (generated by create-s3-website-bucket.sh).
# Website: http://bohdan-sudoku.s3-website.ca-central-1.amazonaws.com/
#
# Usage: $0 [source-dir] [extra args for aws s3 sync]
# Example: $0 ./dist --delete
# Default source when omitted: ./dist (override with UPLOAD_SRC).
#
set -euo pipefail

readonly BUCKET='bohdan-sudoku'
readonly REGION='ca-central-1'

if [[ $# -ge 1 ]]; then
  SRC="$1"
  shift
else
  SRC="${UPLOAD_SRC:-./dist}"
fi

exec aws s3 sync "${SRC}" "s3://${BUCKET}/" --region "${REGION}" "$@"
